### ISSUE TITLE
Is python3 support planing? 

### ISSUE THREAD

**Issue by LuxoftAKutsan** [sobotklp/pycksum#3]

**Comment by sobotklp** [comment]
pycksum is tested on Python 3.2, 3.3., 3.4 and 3.5. See the travis.yml file.
Which version are you having trouble with?

**Comment by LuxoftAKutsan** [comment]
@sobotklp  thanks, is it possible to install it for python3 from pip?

**Comment by sobotklp** [comment]
`pip3 install pycksum` works for me on OSX.

**Comment by LuxoftAKutsan** [comment]
Thanks  a lot!
