### ISSUE TITLE
Issue on windows 7

### ISSUE THREAD

**Issue by pmoubed** [sobotklp/pycksum#5]
C:\>python -m pip install pycksum
Collecting pycksum
  Using cached pycksum-0.4.2.tar.gz
Installing collected packages: pycksum
  Running setup.py install for pycksum ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\XXXXXX\\appdata\\local\\temp\\pip-build-wsbbsb\\pycksum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\XXXXXX\appdata\local\temp\pip-kyhadz-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\pycksum
    copying pycksum\main.py -> build\lib.win32-2.7\pycksum
    copying pycksum\__init__.py -> build\lib.win32-2.7\pycksum
    running build_ext
    building '_pycksum' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\ext
    C:\Users\XXXXXX\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tcext/_pycksum.c /Fobuild\temp.win32-2.7\Release\ext/_pycksum.obj _pycksum.cext/_pycksum.c(235) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\XXXXXX\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\XXXXXX\\appdata\\local\\temp\\pip-build-wsbbsb\\pycksum\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\XXXXXX\appdata\local\temp\pip-kyhadz-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\XXXXXX\appdata\local\temp\pip-build-wsbbsb\pycksum\

**Comment by sobotklp** [comment]
Apparently versions of Visual C++ before Visual Studio 2012 are not C99-compatible. There are some guides on the net about installing your own stdint.h.

Later versions of Visual C++ include stdint.h, so I'd recommend upgrading if you can.

**Comment by sobotklp** [comment]
Timing out
